/** Divisiones político-administrativas de Cuba: 15 provincias + Municipio Especial Isla de la Juventud, con sus municipios. */

export type Provincia = {
  code: string;
  name: string;
  municipios: string[];
};

export const PROVINCIAS: Provincia[] = [
  {
    code: "PR",
    name: "Pinar del Río",
    municipios: [
      "Consolación del Sur",
      "Guane",
      "La Palma",
      "Los Palacios",
      "Mantua",
      "Minas de Matahambre",
      "Pinar del Río",
      "San Juan y Martínez",
      "San Luis",
      "Sandino",
      "Viñales",
    ],
  },
  {
    code: "AR",
    name: "Artemisa",
    municipios: [
      "Alquízar",
      "Artemisa",
      "Bahía Honda",
      "Bauta",
      "Caimito",
      "Candelaria",
      "Guanajay",
      "Güira de Melena",
      "Mariel",
      "San Antonio de los Baños",
      "San Cristóbal",
    ],
  },
  {
    code: "LH",
    name: "La Habana",
    municipios: [
      "Arroyo Naranjo",
      "Boyeros",
      "Centro Habana",
      "Cerro",
      "Cotorro",
      "Diez de Octubre",
      "Guanabacoa",
      "Habana del Este",
      "Habana Vieja",
      "La Lisa",
      "Marianao",
      "Plaza de la Revolución",
      "Playa",
      "Regla",
      "San Miguel del Padrón",
    ],
  },
  {
    code: "MY",
    name: "Mayabeque",
    municipios: [
      "Batabanó",
      "Bejucal",
      "Güines",
      "Jaruco",
      "Madruga",
      "Melena del Sur",
      "Nueva Paz",
      "Quivicán",
      "San José de las Lajas",
      "San Nicolás",
      "Santa Cruz del Norte",
    ],
  },
  {
    code: "MT",
    name: "Matanzas",
    municipios: [
      "Calimete",
      "Cárdenas",
      "Ciénaga de Zapata",
      "Colón",
      "Jagüey Grande",
      "Jovellanos",
      "Limonar",
      "Los Arabos",
      "Martí",
      "Matanzas",
      "Pedro Betancourt",
      "Perico",
      "Unión de Reyes",
    ],
  },
  {
    code: "VC",
    name: "Villa Clara",
    municipios: [
      "Caibarién",
      "Camajuaní",
      "Cifuentes",
      "Corralillo",
      "Encrucijada",
      "Manicaragua",
      "Placetas",
      "Quemado de Güines",
      "Ranchuelo",
      "Remedios",
      "Sagua la Grande",
      "Santa Clara",
      "Santo Domingo",
    ],
  },
  {
    code: "CF",
    name: "Cienfuegos",
    municipios: [
      "Abreus",
      "Aguada de Pasajeros",
      "Cienfuegos",
      "Cruces",
      "Cumanayagua",
      "Lajas",
      "Palmira",
      "Rodas",
    ],
  },
  {
    code: "SS",
    name: "Sancti Spíritus",
    municipios: [
      "Cabaiguán",
      "Fomento",
      "Jatibonico",
      "La Sierpe",
      "Sancti Spíritus",
      "Taguasco",
      "Trinidad",
      "Yaguajay",
    ],
  },
  {
    code: "CA",
    name: "Ciego de Ávila",
    municipios: [
      "Baraguá",
      "Bolivia",
      "Chambas",
      "Ciego de Ávila",
      "Ciro Redondo",
      "Florencia",
      "Majagua",
      "Morón",
      "Primero de Enero",
      "Venezuela",
    ],
  },
  {
    code: "CM",
    name: "Camagüey",
    municipios: [
      "Camagüey",
      "Carlos Manuel de Céspedes",
      "Esmeralda",
      "Florida",
      "Guáimaro",
      "Jimaguayú",
      "Minas",
      "Najasa",
      "Nuevitas",
      "Santa Cruz del Sur",
      "Sibanicú",
      "Sierra de Cubitas",
      "Vertientes",
    ],
  },
  {
    code: "LT",
    name: "Las Tunas",
    municipios: [
      "Amancio",
      "Colombia",
      "Jesús Menéndez",
      "Jobabo",
      "Las Tunas",
      "Majibacoa",
      "Manatí",
      "Puerto Padre",
    ],
  },
  {
    code: "GR",
    name: "Granma",
    municipios: [
      "Bartolomé Masó",
      "Bayamo",
      "Buey Arriba",
      "Campechuela",
      "Cauto Cristo",
      "Guisa",
      "Jiguaní",
      "Manzanillo",
      "Media Luna",
      "Niquero",
      "Pilón",
      "Río Cauto",
      "Yara",
    ],
  },
  {
    code: "HO",
    name: "Holguín",
    municipios: [
      "Antilla",
      "Báguanos",
      "Banes",
      "Cacocum",
      "Calixto García",
      "Cueto",
      "Frank País",
      "Gibara",
      "Holguín",
      "Mayarí",
      "Moa",
      "Rafael Freyre",
      "Sagua de Tánamo",
      "Urbano Noris",
    ],
  },
  {
    code: "SC",
    name: "Santiago de Cuba",
    municipios: [
      "Contramaestre",
      "Guamá",
      "Mella",
      "Palma Soriano",
      "San Luis",
      "Santiago de Cuba",
      "Segundo Frente",
      "Songo-La Maya",
      "Tercer Frente",
    ],
  },
  {
    code: "GT",
    name: "Guantánamo",
    municipios: [
      "Baracoa",
      "Caimanera",
      "El Salvador",
      "Guantánamo",
      "Imías",
      "Maisí",
      "Manuel Tames",
      "Niceto Pérez",
      "San Antonio del Sur",
      "Yateras",
    ],
  },
  {
    code: "IJ",
    name: "Isla de la Juventud",
    municipios: ["Isla de la Juventud"],
  },
];

/** Lookup rápido: code → Provincia */
export const PROVINCIA_MAP = new Map(PROVINCIAS.map((p) => [p.code, p]));

/** Municipios de una provincia por código */
export function getMunicipios(provinciaCode: string): string[] {
  return PROVINCIA_MAP.get(provinciaCode)?.municipios ?? [];
}
