/** Catálogos de sugerencias para el formulario de piezas (mercado cubano). */

export const PART_BRANDS: string[] = [
  "ACDelco",
  "Akebono",
  "ATE",
  "Bosch",
  "Brembo",
  "Castrol",
  "Champion",
  "Continental",
  "Denso",
  "Febi",
  "Gates",
  "Hella",
  "KYB",
  "Mahle",
  "Mann-Filter",
  "Mobil",
  "Monroe",
  "NGK",
  "Philips",
  "Sachs",
  "Shell",
  "TRW",
  "Valeo",
];

export const VEHICLE_MAKES: string[] = [
  "Audi",
  "BMW",
  "BYD",
  "Chery",
  "Chevrolet",
  "Citroën",
  "Dodge",
  "Dongfeng",
  "Fiat",
  "Ford",
  "Great Wall",
  "Honda",
  "Hyundai",
  "Isuzu",
  "JAC",
  "Jeep",
  "Kia",
  "Land Rover",
  "Lexus",
  "Mazda",
  "Maxus",
  "Mercedes-Benz",
  "MG",
  "Mini",
  "Mitsubishi",
  "Nissan",
  "Peugeot",
  "Porsche",
  "RAM",
  "Renault",
  "Subaru",
  "Suzuki",
  "Toyota",
  "Volkswagen",
  "Volvo",
];

export const VEHICLE_MODELS: Record<string, string[]> = {
  Audi: ["A1", "A3", "A4", "A5", "Q2", "Q3", "Q5", "Q7"],
  BMW: ["Serie 1", "Serie 3", "Serie 5", "X1", "X3", "X5", "X6"],
  BYD: ["Atto 3", "Dolphin", "Han", "Song", "Tang", "Yuan Plus"],
  Chery: ["Arrizo 5", "QQ", "Tiggo 2", "Tiggo 3", "Tiggo 4", "Tiggo 7", "Tiggo 8"],
  Chevrolet: ["Captiva", "Colorado", "Cruze", "Onix", "Sail", "Silverado", "Spark", "Spin", "S10", "Tracker"],
  "Citroën": ["Berlingo", "C3", "C4 Cactus", "C5 Aircross", "Jumpy"],
  Dodge: ["Charger", "Durango", "Journey", "RAM 700"],
  Dongfeng: ["AX4", "AX7", "H30", "Joyear", "Rich", "S30"],
  Fiat: ["500", "Argo", "Cronos", "Mobi", "Strada", "Toro"],
  Ford: ["Bronco", "EcoSport", "Edge", "Escape", "Explorer", "F-150", "Fiesta", "Focus", "Kuga", "Mustang", "Ranger"],
  "Great Wall": ["Haval H6", "Hover", "Poer", "Steed", "Wingle"],
  Honda: ["Accord", "City", "Civic", "CR-V", "Fit", "HR-V", "Pilot"],
  Hyundai: ["Accent", "Creta", "Elantra", "Grand i10", "H1", "HB20", "i20", "Kona", "Santa Fe", "Tucson", "Venue"],
  Isuzu: ["D-Max", "MU-X", "NPR", "NQR"],
  JAC: ["J3", "J4", "S2", "S3", "S4", "S5", "T6", "T8"],
  Jeep: ["Cherokee", "Compass", "Gladiator", "Grand Cherokee", "Renegade", "Wrangler"],
  Kia: ["Carnival", "Cerato", "K2500", "Morning", "Picanto", "Rio", "Seltos", "Sorento", "Soul", "Sportage", "Stonic"],
  "Land Rover": ["Defender", "Discovery", "Discovery Sport", "Range Rover", "Range Rover Evoque", "Range Rover Sport"],
  Lexus: ["ES", "IS", "NX", "RX", "UX"],
  Mazda: ["2", "3", "6", "BT-50", "CX-3", "CX-30", "CX-5", "CX-9"],
  Maxus: ["D60", "D90", "T60", "T70", "T90", "V80"],
  "Mercedes-Benz": ["Clase A", "Clase C", "Clase E", "GLA", "GLC", "GLE", "Sprinter"],
  MG: ["3", "5", "GS", "HS", "Pickup", "RX5", "ZS"],
  Mini: ["Clubman", "Cooper", "Countryman"],
  Mitsubishi: ["ASX", "Eclipse Cross", "L200", "Lancer", "Mirage", "Montero", "Montero Sport", "Outlander"],
  Nissan: ["Frontier", "Kicks", "March", "Navara", "Note", "NP300", "Pathfinder", "Qashqai", "Sentra", "Versa", "X-Trail"],
  Peugeot: ["208", "2008", "301", "308", "3008", "5008", "Expert", "Partner"],
  Porsche: ["911", "Cayenne", "Macan", "Panamera"],
  RAM: ["1500", "2500", "3500", "700"],
  Renault: ["Captur", "Duster", "Kangoo", "Koleos", "Kwid", "Logan", "Megane", "Sandero", "Stepway"],
  Subaru: ["Ascent", "Forester", "Impreza", "Legacy", "Outback", "WRX", "XV"],
  Suzuki: ["Alto", "Baleno", "Celerio", "Ciaz", "Grand Vitara", "Jimny", "S-Presso", "Swift", "SX4", "Vitara"],
  Toyota: ["4Runner", "C-HR", "Camry", "Corolla", "Fortuner", "Hiace", "Hilux", "Land Cruiser", "Prius", "RAV4", "Rush", "Tacoma", "Yaris"],
  Volkswagen: ["Amarok", "Gol", "Nivus", "Polo", "Saveiro", "T-Cross", "Tiguan", "Vento", "Virtus"],
  Volvo: ["S60", "V40", "XC40", "XC60", "XC90"],
};

/** Lista plana de todos los modelos (deduplicada y ordenada) para autocompletar
 * cuando aún no se ha elegido marca. */
export const ALL_VEHICLE_MODELS: string[] = Array.from(
  new Set(Object.values(VEHICLE_MODELS).flat()),
).sort((a, b) => a.localeCompare(b, "es"));
